### ISSUE TITLE
sync for other player

### ISSUE THREAD

**Issue by zek0** [thiago-dev/fivem-hypnonema#1]
Thank for script. But video dont sync with other players. It is possible or it is only if we have standalone web server? 

thank you.

**Comment by thiago-dev** [comment]
Currently the video should be synced with everyone online at time of playback. Eg. if someone joins after you've clicked play, this person wouldn't see the video. Which webserver (built-in, nginx or apache) you actually use doesn't really matter - but for security reasons you should use a more mature one, but it doesn't affect the sync however.
