### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DevMinkh** [thiago-dev/fivem-hypnonema#26]
Can you please compile the new version, i'll try it many time but i can't get the environment to run.

Thx for this amazing script "Weiter so ;)"

**Comment by thiago-dev** [comment]
Hey!
I just published a new [release](https://github.com/thiago-dev/fivem-hypnonema/releases/tag/1.8.12.7753).

**Comment by DevMinkh** [comment]
tank you <3
