### ISSUE TITLE
Mature Audience (Twitch)

### ISSUE THREAD

**Issue by ChrisLenga** [thiago-dev/fivem-hypnonema#31]
Currently, right now, it appears that Twitch has recently updated its protocols, and all of a sudden we cannot watch any streams that are regarded as mature audience streams. I have tinkered with it a bit, but can't seem to find a way around this issue.

**Comment by thiago-dev** [comment]
Thank you for reporting this issue.
It should be gone with the [recent](https://github.com/thiago-dev/fivem-hypnonema/commit/368d08ccb376f1cb61e32942b2bb0ed8cab10e83) commit.
