### ISSUE TITLE
TypeError: Failed to fetch (https://thiago-dev.github.io/fivem-hypnonema//:41)

### ISSUE THREAD

**Issue by christerjohansson** [thiago-dev/fivem-hypnonema#34]
Console is spammed with this error... what is it supposed to fetch from the url? Can I host this myself in case your account is not capable of too many request? 

I looked at the gh-pages index.html... but it is only a compressed file with scripts.

**Comment by thiago-dev** [comment]
Hi,

after the recent FiveM NUI changes, the client will now print this error if the callback wasn't returned and/or didn't contain an object.
I already fixed this in a recent commit.
