### ISSUE TITLE
Failed to construct 'URL' : Invalid URL

### ISSUE THREAD

**Issue by loulou123546** [thiago-dev/fivem-hypnonema#35]
Hello,

I seen I got these error from few hours (doesn't know the exact moment when it started to spawn)

![image](https://user-images.githubusercontent.com/20153343/87821126-97af6200-c86f-11ea-9ea8-f310514c94b6.png)

They are spamming something like 10 per seconds, and seem to come from the gh-pages/index.html:41

Actually, the script is still working perfectly, but keeping it active block me from reading the debugs line in the console

These line appear client side, from the start of the server, and continue while playing videos, and even after finished it
(maybe because we have multiple screen)

**Comment by Clems54** [comment]
+1
