### ISSUE TITLE
Missing ArgsReader class in latest commit

### ISSUE THREAD

**Issue by Salzian** [thiago-dev/fivem-hypnonema#37]
The latest commit 368d08ccb376f1cb61e32942b2bb0ed8cab10e83 is missing the ArgsReader class.

Comment: https://github.com/thiago-dev/fivem-hypnonema/commit/368d08ccb376f1cb61e32942b2bb0ed8cab10e83#r40916532

**Comment by mdiazcl** [comment]
+1

**Comment by thiago-dev** [comment]
With commit [f1c6822](https://github.com/thiago-dev/fivem-hypnonema/commit/f1c68226ddf777a057e1cf48628c5d0ede1746cf) the file is now included.
