### ISSUE TITLE
Global Volume, How about Self Volume?

### ISSUE THREAD

**Issue by NightcoreIsla** [thiago-dev/fivem-hypnonema#39]
first.
everyone like different sound volume, and everyone will heared different volume defined by thier audio card/speaker/headphone
so maybe only the settings name "Global Volume" is not a good idea

second.
in public server must be have some badboy tried to delete screens, so will disabled edit/delete screens json post code in es2015.js or other way to anti this happend.
however the global volume is setting on screens detail, so when different player have different like volume, they can't change it too, but the most important for fix this problem,add a self volume control, then every player can setting a like sound volume.

i tried add this function by my self, but the js code was be minifed....
everytime i trying to format that to normal file for easy edit code, will happend much js error....
so even i remove json post code, i was edited when minifed environment, that was hell.

**Comment by thiago-dev** [comment]
This indeed might be an useful feature. Thanks for this suggestion!

Could you provide more information about "some badboy" deleting screens? Normally this should not happen, as prior to every change (CRUD) operation the necessary permission is checked. So if you didn't choose to give everyone the ACE permission (default: command.hypnonema), I really would like to have some more information so I can look further into it.

Nonetheless if you want to make any changes to the NUI interface, just take a look into the "[Hypnonema.NUI](https://github.com/thiago-dev/fivem-hypnonema/tree/master/src/Hypnonema.NUI)" directory in this repository.

**Comment by NightcoreIsla** [comment]
> Could you provide more information about "some badboy" deleting screens? Normally this should not happen, as prior

in public server, not always play vedio by admin, so i give player the command ace.
