### ISSUE TITLE
Error : Exception loading assembly NHttp

### ISSUE THREAD

**Issue by XONXO** [thiago-dev/fivem-hypnonema#4]
I'm having a mistake if you can help me! Thank you
![image](https://user-images.githubusercontent.com/41170060/64721627-ced11c00-d4c4-11e9-8d09-a047d0a4ad6b.png)

**Comment by thiago-dev** [comment]
The file NHttp.dll is missing. Maybe you deleted it?

**Comment by XONXO** [comment]
No
![image](https://user-images.githubusercontent.com/41170060/64753831-90ffe200-d51c-11e9-819e-9ef22795e85d.png)
