### ISSUE TITLE
html call function

### ISSUE THREAD

**Issue by ljg96** [thiago-dev/fivem-hypnonema#41]
Third party player transmission function
I want to use ovenplayer.

However, it is not supported.
  Is there any way to send the .html link?
As the distance increases
You should be able to call about:blank.

**Comment by thiago-dev** [comment]
What do you mean in this context with 

> Is there any way to send the .html link?

There is already the possibility to make use of third party players.
Take a look at https://github.com/CookPete/react-player#adding-custom-players


> As the distance increases
You should be able to call about:blank.

Why would you want to do this?

**Comment by ljg96** [comment]
Thank you for your answer, I need it to save traffic.

**Comment by ljg96** [comment]
I don't understand it. Is there a way to apply that to my oven player? It is a webrtc player.

**Comment by ljg96** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>

    <title>OvenPlayer</title>
    <link rel="stylesheet" href="lib/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">

    
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-40491361-8"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-40491361-8');
    </script>

    <script src="http://fireworkmen.mooo.com/oven/docs/lib/vue.min.js"></script>
    <script src="http://fireworkmen.mooo.com/oven/docs/lib/dash.all.debug.js"></script>
    <script src="http://fireworkmen.mooo.com/oven/docs/lib/clipboard.min.js"></script>
    <script src="http://fireworkmen.mooo.com/oven/docs/lib/jquery-1.12.4.min.js"></script>
    <script src="http://fireworkmen.mooo.com/oven/docs/lib/popper.min.js"></script>
    <script src="http://fireworkmen.mooo.com/oven/docs/lib/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
    <script src="http://fireworkmen.mooo.com/oven/docs/lib/dash.all.debug.js"></script>
    
    <script src="http://fireworkmen.mooo.com/oven/dist/development/ovenplayer/ovenplayer.js"></script>
	<script src='https://unpkg.com/react-player/dist/ReactPlayer.standalone.js'></script>
</head>
<body>
            <div id="player"></div>

 

<script>

    var navProtocol = window.location.protocol;
    var wsProtocol = 'ws:';
    var httpProtocol = 'http:';
    var signallingPort = ':3333';
    var httpStreamingPort = ':80';

    if (navProtocol === 'https:') {
        wsProtocol = 'ws:';
        httpProtocol = 'https:';
        signallingPort = ':3334';
        httpStreamingPort = ':443';
    }

    var player = "", errorOccured = false;

    $(document).ready(function () {

        omeURL = [
            {
                type: 'webrtc',
                file: wsProtocol + '//xxx' + signallingPort + '/xxx/xxx',
                label: 'WebRTC'
            },
        ];

        player = OvenPlayer.create("player", {
            autoStart: true,
            autoFallback: false,
			controls:false,
            sources: omeURL
        });
        player.on("ready", function (data) {
            errorOccured = false;

        });
        player.on("stateChanged", function (data) {
            if (data && data.newstate && (data.newstate === "playing" || data.newstate === "pause")) {
                navigation.titleStatus = "LIVE";
            }
        });
        player.on("error", function (error) {
            errorOccured = true;
            console.log(error);
            navigation.errorMessage = error.message;
            navigation.titleStatus = "OFFLINE";
        });

    });

    var navigation = new Vue({
        el: '#demo-navi',
        data: {
            errorMessage: "",
            titleStatus: "loading..."
        },
        methods: {
            loadSources: function () {

                if (!player) {
                    return;
                }

                player.remove();
                player = OvenPlayer.create("player", {
                    autoStart: true,
                    autoFallback: false,
                    sources: omeURL
                });

                player.on("ready", function (data) {
                    errorOccured = false;

                });
                player.on("stateChanged", function (data) {
                    if (data && data.newstate && (data.newstate === "playing" || data.newstate === "pause")) {
                        navigation.titleStatus = "LIVE";
                    }
                });
                player.on("error", function (error) {
                    errorOccured = true;
                    console.log(error);
                    navigation.errorMessage = error.message;
                    navigation.titleStatus = "OFFLINE";
                });

            }
        }
    });


</script>
</body>
</html>

**Comment by ljg96** [comment]
![image](https://user-images.githubusercontent.com/61880302/92589688-e3154800-f2d5-11ea-878e-b5116e693bf6.png)
Can't live broadcasts be played?

**Comment by ljg96** [comment]
How to send the html itself to the screen ex) http://google.com

**Comment by ljg96** [comment]
I want to ask for help, do you have a discord?
https://discord.gg/BND8VQw
