### ISSUE TITLE
Failed to read currentTime

### ISSUE THREAD

**Issue by Ayoubsaif** [thiago-dev/fivem-hypnonema#43]
![imagen](https://user-images.githubusercontent.com/34210464/93721510-13d86580-fb91-11ea-88f9-1386aea16bd1.png)
I have this message spamming all day on the command line and that bothers to see other errors.
If it can be disabled in any way it is appreciated

Thanks for all,

**Comment by dutchplayers** [comment]
Same

**Comment by tobipazos25** [comment]
me too, anyone can help?

**Comment by gotzonot** [comment]
Same

**Comment by Kuhicop** [comment]
same error here

**Comment by SajithDL** [comment]
same 😣

**Comment by eysi24** [comment]
any solution for this?

**Comment by GrapsZ** [comment]
I've fix it on my server.
If you want i can release it soon.
As you want.

**Comment by roobr** [comment]
hey @GrapsZ Would be good to see how you have fixed this

**Comment by GrapsZ** [comment]
> hey @GrapsZ Would be good to see how you have fixed this

This this message is a simple debug print in ArgsReader.cs. If' you want to fix it, you can just adding one bool variable like : debugMode and set it false in fxmanifest.lua.

If you can't make modification for any reason i can share my release..

**Comment by Shark911** [comment]
I think we would like your release!

**Comment by ravorrr** [comment]
I think so too 😄

**Comment by krizmatic** [comment]
@GrapsZ Could you please share your release ? It might be helpful.

**Comment by FuriousLeech** [comment]
> > hey @GrapsZ Would be good to see how you have fixed this
> 
> This this message is a simple debug print in ArgsReader.cs. If' you want to fix it, you can just adding one bool variable like : debugMode and set it false in fxmanifest.lua.
> 
> If you can't make modification for any reason i can share my release..

can you please release this, or go into more detail?

**Comment by GrapsZ** [comment]
I'll share that (compiled version and source this weekend. I was busy with my job.

**Comment by GrapsZ** [comment]
Sources : https://github.com/GrapsZ/Hypnonema-spamFix

Just read and download at : https://github.com/GrapsZ/Hypnonema-spamFix/releases/tag/1.9

- [ ]  I've made that for my server. This is just a simple solution to fix that fucking spam. 

- [ ]  Open then fxmanifest file and edit it has you want.

Kiss 👍

**Comment by Shark911** [comment]
Thanks! ❤️

**Comment by FuriousLeech** [comment]
> Sources : https://github.com/GrapsZ/Hypnonema-spamFix
> 
> Just read and download at : https://github.com/GrapsZ/Hypnonema-spamFix/releases/tag/1.9
> 
> * [x]   I've made that for my server. This is just a simple solution to fix that fucking spam.
> * [x]   Open the fxmanifest file and edit it has you want.
> 
> Edit :
> 
> You can check how i fix spamming message here :
> 
> [GrapsZ/Hypnonema-spamFix@06c759b#diff-c371493f5a66b609540b68b35d837de2bb85bf3f0fe788360d2509fefff710baR25](https://github.com/GrapsZ/Hypnonema-spamFix/commit/06c759b3375ba482ebedf7f1f2faa2f1c4990355#diff-c371493f5a66b609540b68b35d837de2bb85bf3f0fe788360d2509fefff710baR25)
> 
> and compare with the original here :
> 
> https://github.com/thiago-dev/fivem-hypnonema/blob/master/src/Hypnonema.Client/ArgsReader.cs#L23
> 
> Kiss 👍

Really appreciate it. Lifesafer!!

**Comment by evilstriker** [comment]
Here is the fix for it just download this file and replace it with the existing "Hypnonema.Client.net.dll" ;)

https://github.com/evilstriker/hypnonema

**Comment by thiago-dev** [comment]
https://github.com/thiago-dev/fivem-hypnonema/releases/tag/1.8.23.4-alpha should fix this issue. Could you please test it and report back in case of any encountered errors?

**Comment by thiago-dev** [comment]
Fixed in https://github.com/thiago-dev/fivem-hypnonema/releases/tag/1.9.0
