### ISSUE TITLE
Twtch stream unavailable due "not supported browser"

### ISSUE THREAD

**Issue by Knaak53** [thiago-dev/fivem-hypnonema#45]
I just tested it for forst time everything works well but no twitch, it is like hypnonema do every that it should do accordly but tehre is some is not taking in count, maybe video format? any way a image worth more than 1000 words:

![imagen](https://user-images.githubusercontent.com/9432787/100803396-648afb00-342b-11eb-9d69-46cc433e952d.png)

WIth this feature fixed it would be just wonderfull. Great work!

**Comment by S020** [comment]
![imagen](https://user-images.githubusercontent.com/74140365/101227687-0a8f6d00-3699-11eb-88a4-1e0299182532.png)
Youtube too

**Comment by sedres13** [comment]
Same for me someone solved it?

**Comment by GamersReturn** [comment]
Same here cant play any Live Video

**Comment by tiagofcp** [comment]
any solutions for this?

**Comment by LeqitFoxHDYT** [comment]
Hi,

i had the same problem.

I fixed it:

You must paste this in "fxmanifest.lua":

hypnonema_http_server 'true'
hypnonema_listen_addr '0.0.0.0'
hypnonema_http_port '80'

Then it should works!
