### ISSUE TITLE
TypeError: Failed to construct: 'URL': Invalid URL (https://thiago-dev.github.io/fivem-hypnonema/index.html:1)

### ISSUE THREAD

**Issue by AlexMartSch** [thiago-dev/fivem-hypnonema#46]
This error starts popping up in the console all the time, then I can't use the script properly.

![image](https://user-images.githubusercontent.com/5489500/102025986-39cd6a80-3d7a-11eb-86a1-762c4293210c.png)

**Comment by bashon1** [comment]
some issue and when i disbale this url script stop working to play video

**Comment by Salzian** [comment]
Can confirm. It spams the console so fast it bloats the local log files with megabytes of data in no time.

**Comment by Salzian** [comment]
So we ran some more tests. The issue only occurred on our live server so far. Localhost does not spam the error for some reason. I then proceeded to host the webplayer (wwwroot) on our own server but quickly found out that the issue must be some sort of TypeScript error within the webplayer, not the base resource on the server itself. 

Unfortunately we did not found a workaround or solution yet. From my gut feeling it must be a bug in the webplayer, but I'm not even sure which folder that is in the repo.

**Comment by thiago-dev** [comment]
Can you tell me if you are still experiencing this issue and if yes which url you are trying to play?

**Comment by cainrivera961** [comment]
Yes we are nobody can use hypnoenma we've taiken it out the server cause the hhuge hitches, please help im willing to test i did add u on discord
TrueOne#8575

**Comment by cainrivera961** [comment]
I dont have a spam issue anymore but i have an issue where it says 
https://i.gyazo.com/93c49e0dd90b0c9e607884694b869e03.png

port 41 issue

**Comment by spacejezus** [comment]
> Can you tell me if you are still experiencing this issue and if yes which url you are trying to play?

i saw you made a new source build but no new release. are you still testing this? or could you build it as a beta release so we can see if it's fixed?
