### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by djplus81** [thiago-dev/fivem-hypnonema#71]
![Screenshot 2021-11-05 215016](https://user-images.githubusercontent.com/90886403/140593904-bc5edb1b-ef1e-4597-8edc-42c8c23027cc.png)

**Comment by thiago-dev** [comment]
duplicate of #43

**Comment by djplus81** [comment]
duplicate of #43

**Comment by djplus81** [comment]
So which command should I duplicate or just should I put #43 twice?
