### ISSUE TITLE
How can i solve this problem

### ISSUE THREAD

**Issue by djplus81** [thiago-dev/fivem-hypnonema#72]
![Screenshot 2021-11-05 215016](https://user-images.githubusercontent.com/90886403/140628176-57c4ccc0-cce5-4f21-b8be-43b2955f022b.png)

How can i solve this problem

**Comment by djplus81** [comment]
this is my Email Dj_alex_plus81@msn.com

**Comment by thiago-dev** [comment]
I'm already aware of that bug. A fix addressing the current known issues will come probably later this month. 

In the meanwhile: #43 some people have already provided some workarounds/fixes on their own.

**Comment by djplus81** [comment]
ho ok thank you
