### ISSUE TITLE
Cannot read property 'payload' of undefined...

### ISSUE THREAD

**Issue by ravorrr** [thiago-dev/fivem-hypnonema#76]
An error that appears in the console:

![1](https://user-images.githubusercontent.com/71786442/153841932-6a37ca81-edc2-4312-88bc-0149ec89dc12.png)

This error applies to pre-release version (1.8.23.4). Yes, the error ("failed to read currentTime") disappeared, but the one presented above appeared, it additionally limits the possibility of using the functions offered by hypnonema (you can not run anything via HypnonemaNUI).

I know this is a beta version, but it seems to me that sooner or later it would be useful to fix this bug, because it is quite inconvenient.
Thank you and best regards 😉

**Comment by thiago-dev** [comment]
The codebase went through a heavy refactoring procedure and I introduced some smaller improvements. I am still not finished yet so you may expect errors to occur (especially if you are using a url created for testing purposes only 😄 ). 

But nonetheless: I'm about to finish the tests of all changes soon, so I can publish a new release which fixes some major issues. 

Stay tuned!
