### ISSUE TITLE
 You are no permited to play on this screen. missin ace: "hypnonema.playback.play"

### ISSUE THREAD

**Issue by vixmxstudio** [thiago-dev/fivem-hypnonema#77]
I have tried to reproduce already add the permissions to the server.cfg but nothing, also enable the permissions in the permissions.cfg file but nothing

You are no permited to play on this screen. missin ace:

"hypnonema.playback.play"

**Comment by daveayee** [comment]
Have you set up permissions in server.cfg?

**Comment by thiago-dev** [comment]
Did you setup ACE Permissions on your server correctly?
Per default you need to be part of the group.admin to make use of the command.

For more informations on how to setup ACEs take a look at this guide: https://forum.cfx.re/t/basic-aces-principals-overview-guide/90917

**Comment by minipunch** [comment]
I ran into this also

I thought you were supposed to be able to tweak `permissions.cfg` to allow anyone to use it? non-admins?

I tried but to no avail

**Comment by thiago-dev** [comment]
To allow everyone to do anything with hypnonema you need `add_ace builtin.everyone hypnonema allow` in `permissions.cfg`
