### ISSUE TITLE
Very low Volume.

### ISSUE THREAD

**Issue by daveayee** [thiago-dev/fivem-hypnonema#78]
The Volume is very low  in the new update. Need to be standing right in front of the screen to hear it.

Is there a way to increase the volume?

Increasing the distance gives this error.
![unknown (1)](https://user-images.githubusercontent.com/70829460/154791426-a6a75b0d-e92e-4edd-810a-79d562786191.png)

**Comment by thiago-dev** [comment]
You can increase the volume either by editing your screen and setting the values for soundMaxDistance etc. (you have to disable 3D Audio for it, it is temporarily not available in the newest update) or by using the command /hypnonema volume 100 for example to set the local volume to 100.

Unfortunately I can't reproduce the error you send, could you please describe which steps you did to get that error?

**Comment by daveayee** [comment]
I ended up removing the 3d sound and could adjust the volume that way.  Works great now and is much better on the resmon now too. Thanks
