### ISSUE TITLE
Feat Req  - Screen Stats

### ISSUE THREAD

**Issue by Rosw3lluk** [thiago-dev/fivem-hypnonema#79]
Heya Bud, is there a way to see if a video is "currently" playing etc.. via another resource? if not is there anyway to implement such a feature?

Regards
Roswell

**Comment by thiago-dev** [comment]
Yes, it's definitely possible! I'll add the required exports to get the player states in the next few days.

**Comment by thiago-dev** [comment]
[Implemented](https://github.com/thiago-dev/fivem-hypnonema#getduistate) in [1.9.1](https://github.com/thiago-dev/fivem-hypnonema/releases/tag/1.9.1).
