### ISSUE TITLE
Command doesn't work anymore since new version

### ISSUE THREAD

**Issue by KarliCarlos** [thiago-dev/fivem-hypnonema#83]
Since the new Version the command doesn’t work anymore. When I just put the folder into ressources and start it, it doesn’t work because it can’t find a fxmanifest.lua file. So I renamed src hypnonema, put it it the resource folder and put the stream folder into the hypnonema folder. Now when I try to execute the command I get this: SYSTEM: hypnonema is not an valid command!

**Comment by rhapidfyre** [comment]
Version 1.9.0 works for me. Changed the command to 'videos' and still works.

**Comment by KarliCarlos** [comment]
Sorry forgot to close the issue. I downloaded the wrong version
