### ISSUE TITLE
client/html/main.js error can't add screen or play video

### ISSUE THREAD

**Issue by dekzaman** [thiago-dev/fivem-hypnonema#89]
For 2 days already I have this error but I haven’t change any code
[https://imgur.com/a/hkiTCvx](url)

**Comment by Baelroak** [comment]
> For 2 days already I have this error but I haven’t change any code [https://imgur.com/a/hkiTCvx](url)

same here

**Comment by dekzaman** [comment]
don't have any fixed?

**Comment by AamiRobin** [comment]
same issue here

**Comment by dekzaman** [comment]
notthings update from dev?

**Comment by BenoursonJ** [comment]
Same error here, any news from @thiago-dev ?

**Comment by dekzaman** [comment]
maybe this script discontinued?

**Comment by daveayee** [comment]
Has also stopped working for me

`
[    740563] [b2372_GTAProce]             MainThrd/   at CitizenFX.Core.EventHandlerEntry+<Invoke>d__5.MoveNext () [0x0008c] in C:\gl\builds\master\fivem\code\client\clrcore\EventHandlerDictionary.cs:111 
[    753500] [b2372_GTAProce]        CrBrowserMain/ [object Object] (@hypnonema/client/html/main.js:1)
[    779766] [b2372_GTAProce]               Render/ Changing video mode.
[    779922] [b2372_GTAProce]               Render/ Changing video mode success: 1.
[    779969] [b2372_GTAProce]               Render/ Creating backbuffer.
[    779969] [b2372_GTAProce]               Render/ Done creating backbuffer.
[    779969] [b2372_GTAProce]               Render/ Changing video mode.
[    780047] [b2372_GTAProce]               Render/ Changing video mode success: 1.
[    782531] [b2372_GTAProce]             MainThrd/ Stopping resource hypnonema
[    782531] [b2372_GTAProce]             MainThrd/ Creating script environments for hypnonema
[    782531] [b2372_GTAProce]             MainThrd/ Instantiated instance of script Hypnonema.Server.BaseServer.
[    782531] [b2372_GTAProce]             MainThrd/ Started resource hypnonema
[    782531] [b2372_GTAProce]             MainThrd/ 
[    782578] [b2372_GTAProce]             MainThrd/ OnConnectionProgress: Downloading content manifest...
[    782610] [b2372_GTAProce]  UV loop: httpClient/ Required resources: hypnonema 
[    782625] [b2372_GTAProce]             MainThrd/ Creating script environments for hypnonema
[    782766] [b2372_GTAProce]             MainThrd/ Loaded Hypnonema.Client.net, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_2123319554
[    782781] [b2372_GTAProce]             MainThrd/ Loaded Hypnonema.Shared, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_2123319554
[    782781] [b2372_GTAProce]             MainThrd/ Instantiated instance of script Hypnonema.Client.ClientScript.
[    782781] [b2372_GTAProce]             MainThrd/ OnConnectionProgress: Mounted hypnonema (1 of 1)
[    782844] [b2372_GTAProce]             MainThrd/ Failed to run a tick for ClientScript: System.Security.VerificationException: Error verifying Hypnonema.Client.Communications.NetworkMethod`2:Invoke (T1,T2): Could not merge stack at depth 4, types not compatible: string (Complex) X T1 ([boxed] Complex) at 0x0023

[    782844] [b2372_GTAProce]             MainThrd/   at Hypnonema.Client.Dui.DuiStateHelper.RequestDuiState () [0x00012] in <265e5cede4e041609351fec272d200e3>:0 

[    782844] [b2372_GTAProce]             MainThrd/   at Hypnonema.Client.Dui.DuiStateHelper.RequestDuiStateAsync () [0x00006] in <265e5cede4e041609351fec272d200e3>:0 

[    782844] [b2372_GTAProce]             MainThrd/   at Hypnonema.Client.ClientScript+<SynchronizeState>d__24.MoveNext () [0x0001e] in <265e5cede4e041609351fec272d200e3>:0 

[    782844] [b2372_GTAProce]             MainThrd/ --- End of stack trace from previous location where exception was thrown ---

[    782844] [b2372_GTAProce]             MainThrd/   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782844] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782844] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782860] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782860] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782860] [b2372_GTAProce]             MainThrd/   at Hypnonema.Client.ClientScript+<OnFirstTick>d__21.MoveNext () [0x000b5] in <265e5cede4e041609351fec272d200e3>:0 
[    782860] [b2372_GTAProce]             MainThrd/ 
[    782891] [b2372_GTAProce]             MainThrd/ Loaded Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed into ScriptDomain_2123319554
[    782891] [b2372_GTAProce]             MainThrd/ Error invoking callback for event __cfx_nui:requestState: System.Security.VerificationException: Error verifying Hypnonema.Client.Communications.NetworkMethod`2:Invoke (T1,T2): Could not merge stack at depth 4, types not compatible: string (Complex) X T1 ([boxed] Complex) at 0x0023

[    782891] [b2372_GTAProce]             MainThrd/   at Hypnonema.Client.Dui.DuiStateHelper.RequestDuiState () [0x00012] in <265e5cede4e041609351fec272d200e3>:0 

[    782891] [b2372_GTAProce]             MainThrd/   at Hypnonema.Client.Dui.DuiStateHelper.RequestDuiStateAsync () [0x00006] in <265e5cede4e041609351fec272d200e3>:0 

[    782891] [b2372_GTAProce]             MainThrd/   at Hypnonema.Client.ScreenPlaybackManager+<OnRequestState>d__54.MoveNext () [0x00014] in <265e5cede4e041609351fec272d200e3>:0 

[    782891] [b2372_GTAProce]             MainThrd/ --- End of stack trace from previous location where exception was thrown ---

[    782891] [b2372_GTAProce]             MainThrd/   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782906] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782906] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782906] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782906] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782906] [b2372_GTAProce]             MainThrd/   at Hypnonema.Client.ClientScript+<>c__DisplayClass15_0+<<RegisterNuiCallback>b__0>d.MoveNext () [0x00073] in <265e5cede4e041609351fec272d200e3>:0 

[    782906] [b2372_GTAProce]             MainThrd/ --- End of stack trace from previous location where exception was thrown ---

[    782906] [b2372_GTAProce]             MainThrd/   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782906] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782906] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782906] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782906] [b2372_GTAProce]             MainThrd/   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    782906] [b2372_GTAProce]             MainThrd/   at CitizenFX.Core.EventHandlerEntry+<Invoke>d__5.MoveNext () [0x0008c] in C:\gl\builds\master\fivem\code\client\clrcore\EventHandlerDictionary.cs:111 
[    783516] [b2372_GTAProce]        CrBrowserMain/ [object Object] (@hypnonema/client/html/main.js:1)
[    786250] [b2372_GTAProce]               Render/ Changing video mode.
[    786375] [b2372_GTAProce]               Render/ Changing video mode success: 1.
`
