### ISSUE TITLE
error while starting 

### ISSUE THREAD

**Issue by TobseNatoR** [thiago-dev/fivem-hypnonema#92]
[[https://imgur.com/a/hkiTCvx](https://github.com/thiago-dev/fivem-hypnonema/issues/url)](https://user-images.githubusercontent.com/103046965/161760411-3eab8b20-3fe2-4350-b77a-179c52a49b2c.jpg)

**Comment by angel-luis** [comment]
[https://imgur.com/a/hkiTCvx](https://github.com/thiago-dev/fivem-hypnonema/issues/url)

**Comment by erayko-dev** [comment]
getting the same

**Comment by evilstriker** [comment]
Same here I think it needs an update @thiago-dev

**Comment by stewiehell** [comment]
same

**Comment by dekzaman** [comment]
3 weeks already same error

**Comment by sp19851** [comment]
same

**Comment by ecco95** [comment]
Same yes
